export const BADGES = {
  hookedOnce: {
    id: 'hooked-once',
    name: 'Hooked Once',
    message: 'You saw how phishing hooks work from the inside.',
    icon: 'hook',
  },
  sharpEyes: {
    id: 'sharp-eyes',
    name: 'Sharp Eyes',
    message: 'You caught the bait before it caught you.',
    icon: 'eye',
  },
  burnedTwice: {
    id: 'burned-twice',
    name: 'Burned Twice, Wiser Once',
    message: 'You spotted the professional double bluff and verified out-of-band.',
    icon: 'flame',
  },
  patternBeginner: {
    id: 'pattern-recognition-beginner',
    name: 'Pattern Recognition — Beginner',
    message: 'You spotted cyberbullying patterns beyond the obvious insults.',
    icon: 'eye',
  },
  digitalDefenderLevel2: {
    id: 'digital-defender-level-2',
    name: 'Digital Defender — Level 2',
    message: 'You traced accountability through a viral pile-on.',
    icon: 'shield',
  },
  humanFirewallBeginner: {
    id: 'human-firewall-beginner',
    name: 'Human Firewall - Beginner',
    message: 'You verified a friendly face before opening a secure door.',
    icon: 'shield',
  },
  humanFirewall: {
    id: 'human-firewall',
    name: 'Human Firewall',
    message: 'You stopped an internal impersonation attempt by verifying first.',
    icon: 'shield',
  },
  networkNavigator: {
    id: 'network-navigator',
    name: 'Network Navigator',
    message: 'You avoided a rogue public Wi-Fi trap.',
    icon: 'shield',
  },
  eyesOpenBeginner: {
    id: 'eyes-open-beginner',
    name: 'Eyes Open - Beginner',
    message: 'You reviewed AI-manipulated evidence without over-trusting the image.',
    icon: 'eye',
  },
}

export const BADGE_CATALOG = [
  { id: 'first-case', name: 'First Case' },
  { id: 'phishing-pro', name: 'Phishing Pro' },
  { id: 'quiz-streak', name: 'Quiz Streak' },
  { id: 'squad-up', name: 'Squad Up' },
  { id: 'veteran', name: 'Veteran' },
  { id: 'sharp-eye', name: 'Sharp Eye' },
  BADGES.sharpEyes,
  BADGES.hookedOnce,
  BADGES.burnedTwice,
  BADGES.patternBeginner,
  BADGES.digitalDefenderLevel2,
  BADGES.humanFirewallBeginner,
  BADGES.humanFirewall,
  BADGES.networkNavigator,
  BADGES.eyesOpenBeginner,
  { id: 'night-owl', name: 'Night Owl' },
  { id: 'perfect-run', name: 'Perfect Run' },
  { id: 'mentor', name: 'Mentor' },
  { id: 'collector', name: 'Collector' },
  { id: 'unbreakable', name: 'Unbreakable' },
  { id: 'unit-zero', name: 'Unit Zero' },
]
